name: Paper

on:
  push:
    branches:
      - main
    paths:
      - "paper.md"
      - ".github/workflows/paper.yml"
  pull_request:
    branches:
      - main
    paths:
      - "paper.md"
      - ".github/workflows/paper.yml"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install/update dependencies
        run: |
          npm install -g npm@latest
          npm install -g myst-cli
          sudo apt-get install -y texlive-latex-extra texlive-publishers texlive-xetex latexmk
      - name: Build the paper
        run: |
          rm -rf outputs
          myst build paper.md --docx --tex --pdf
      - name: Commit the changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add .
          git commit -m "Build paper for ${{ github.sha }}" || true
      - name: Push the changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
